/**
 * EduBek — Digital Twins barrel export.
 *
 * Phase 5A.1: Autonomous Classroom Operations & Digital Twin Platform.
 */
// Service
export {
  syncTwin,
  getTwin,
  listTwinsByType,
  getTwinHistory,
  syncClassroomTwin,
  getClassroomTwin,
  syncStudentTwin,
  getStudentTwin,
  syncTeacherTwin,
  getTeacherTwin,
  syncInstitutionTwin,
  getInstitutionTwin,
  createCalendar,
  getCalendar,
  listCalendars,
  activateCalendar,
  addCalendarEvent,
  listCalendarEvents,
  removeCalendarEvent,
  getUpcomingEventsForScope,
  getHolidaysInRange,
  isWorkingDay,
  prepareNextWeek,
  executeAutonomousInstruction,
  triggerWorkflow,
  getWorkflow,
  listWorkflows,
  listWorkflowTriggers,
  storeAcademicMemory,
  recallAcademicMemory,
  getStudentTrajectory,
  getClassroomHistory,
  getAcademicMemoryById,
  runScenario,
  getScenario,
  listScenarios,
  generateOperations,
  getOperations,
  acknowledgeOperation,
  resolveOperation,
  dismissOperation,
} from "./service";

// Types
export type {
  TwinType,
  DigitalTwinDto,
  ClassroomTwinState,
  StudentTwinState,
  TeacherTwinState,
  InstitutionTwinState,
  AcademicCalendarDto,
  CalendarEventType,
  CalendarEventDto,
  AcademicWorkflowTrigger,
  AcademicWorkflowStep,
  AcademicWorkflowDto,
  AcademicMemoryScope,
  AcademicMemoryType,
  AcademicMemoryDto,
  ScenarioType,
  ScenarioPlanDto,
  AcademicOperationType,
  AcademicOperationDto,
  OperationsCenterDto,
} from "./types";
