/**
 * EduBek — Content translation repository.
 *
 * Direct Prisma access for ResourceTranslation, CategoryTranslation,
 * and SubscriptionPlanTranslation. The ONLY layer that imports `db`
 * for translation operations.
 */
import { db } from "@/lib/db";

// ---------------------------------------------------------------------------
// Resource translations
// ---------------------------------------------------------------------------

export async function findResourceTranslations(resourceId: string) {
  return db.resourceTranslation.findMany({
    where: { resourceId },
    orderBy: { language: "asc" },
  });
}

export async function findResourceTranslation(resourceId: string, language: string) {
  return db.resourceTranslation.findUnique({
    where: {
      resourceId_language: { resourceId, language },
    },
  });
}

export async function createResourceTranslation(input: {
  resourceId: string;
  language: string;
  title: string;
  description?: string;
  content?: string;
  translationStatus?: string;
  translatedBy?: string;
  translationProvider?: string;
  isAutoGenerated?: boolean;
  slug?: string;
}) {
  return db.resourceTranslation.create({
    data: {
      resourceId: input.resourceId,
      language: input.language,
      title: input.title,
      description: input.description ?? null,
      content: input.content ?? "{}",
      translationStatus: input.translationStatus ?? "draft",
      translatedBy: input.translatedBy ?? null,
      translationProvider: input.translationProvider ?? null,
      isAutoGenerated: input.isAutoGenerated ?? false,
      slug: input.slug ?? null,
      translatedAt: new Date(),
    },
  });
}

export async function updateResourceTranslation(
  resourceId: string,
  language: string,
  data: {
    title?: string;
    description?: string | null;
    content?: string;
    translationStatus?: string;
    translatedBy?: string | null;
    translationProvider?: string | null;
    translationVersion?: number;
    isAutoGenerated?: boolean;
    slug?: string | null;
  },
) {
  return db.resourceTranslation.update({
    where: { resourceId_language: { resourceId, language } },
    data: {
      ...data,
      translatedAt: new Date(),
    },
  });
}

export async function deleteResourceTranslation(resourceId: string, language: string) {
  return db.resourceTranslation.delete({
    where: { resourceId_language: { resourceId, language } },
  });
}

export async function countResourceTranslations(resourceId: string): Promise<number> {
  return db.resourceTranslation.count({ where: { resourceId } });
}

// ---------------------------------------------------------------------------
// Category translations
// ---------------------------------------------------------------------------

export async function findCategoryTranslations(categoryId: string) {
  return db.categoryTranslation.findMany({
    where: { categoryId },
    orderBy: { language: "asc" },
  });
}

export async function findCategoryTranslation(categoryId: string, language: string) {
  return db.categoryTranslation.findUnique({
    where: {
      categoryId_language: { categoryId, language },
    },
  });
}

export async function upsertCategoryTranslation(input: {
  categoryId: string;
  language: string;
  name: string;
  description?: string;
  slug?: string;
}) {
  return db.categoryTranslation.upsert({
    where: {
      categoryId_language: { categoryId: input.categoryId, language: input.language },
    },
    create: {
      categoryId: input.categoryId,
      language: input.language,
      name: input.name,
      description: input.description ?? null,
      slug: input.slug ?? null,
    },
    update: {
      name: input.name,
      description: input.description ?? null,
      slug: input.slug ?? null,
    },
  });
}

// ---------------------------------------------------------------------------
// Subscription plan translations
// ---------------------------------------------------------------------------

export async function findPlanTranslations(planId: string) {
  return db.subscriptionPlanTranslation.findMany({
    where: { planId },
    orderBy: { language: "asc" },
  });
}

export async function findPlanTranslation(planId: string, language: string) {
  return db.subscriptionPlanTranslation.findUnique({
    where: {
      planId_language: { planId, language },
    },
  });
}

export async function upsertPlanTranslation(input: {
  planId: string;
  language: string;
  name: string;
  description?: string;
  features?: string;
}) {
  return db.subscriptionPlanTranslation.upsert({
    where: {
      planId_language: { planId: input.planId, language: input.language },
    },
    create: {
      planId: input.planId,
      language: input.language,
      name: input.name,
      description: input.description ?? null,
      features: input.features ?? null,
    },
    update: {
      name: input.name,
      description: input.description ?? null,
      features: input.features ?? null,
    },
  });
}
