/**
 * EduBek — Content translation Zod schemas.
 */
import { z } from "zod";

export const translationStatusSchema = z.enum([
  "draft", "reviewing", "approved", "published", "outdated", "missing",
]);

export const translationProviderSchema = z.enum([
  "ai", "manual", "google", "deepl",
]);

export const createResourceTranslationBodySchema = z.object({
  language: z.string().min(2).max(5),
  title: z.string().min(1).max(500),
  description: z.string().max(5_000).optional(),
  content: z.string().optional(),
  translationStatus: translationStatusSchema.default("draft"),
  translationProvider: translationProviderSchema.optional(),
  isAutoGenerated: z.boolean().default(false),
  slug: z.string().max(200).optional(),
});
export type CreateResourceTranslationBody = z.infer<typeof createResourceTranslationBodySchema>;

export const updateResourceTranslationBodySchema = z.object({
  title: z.string().min(1).max(500).optional(),
  description: z.string().max(5_000).nullable().optional(),
  content: z.string().optional(),
  translationStatus: translationStatusSchema.optional(),
  translationProvider: translationProviderSchema.optional(),
  translationVersion: z.number().int().min(0).optional(),
  isAutoGenerated: z.boolean().optional(),
  slug: z.string().max(200).nullable().optional(),
});
export type UpdateResourceTranslationBody = z.infer<typeof updateResourceTranslationBodySchema>;

export const upsertCategoryTranslationBodySchema = z.object({
  language: z.string().min(2).max(5),
  name: z.string().min(1).max(200),
  description: z.string().max(2_000).optional(),
  slug: z.string().max(200).optional(),
});
export type UpsertCategoryTranslationBody = z.infer<typeof upsertCategoryTranslationBodySchema>;

export const upsertPlanTranslationBodySchema = z.object({
  language: z.string().min(2).max(5),
  name: z.string().min(1).max(200),
  description: z.string().max(2_000).optional(),
  features: z.record(z.string(), z.unknown()).optional(),
});
export type UpsertPlanTranslationBody = z.infer<typeof upsertPlanTranslationBodySchema>;

export const aiTranslateBodySchema = z.object({
  language: z.string().min(2).max(5),
});
export type AiTranslateBody = z.infer<typeof aiTranslateBodySchema>;
