/**
 * EduBek — Content translation service.
 *
 * Phase 4E.5: Universal translation service for all educational content.
 *
 * Provides:
 *   - Resource translation CRUD (create, read, update, delete)
 *   - Category translation upsert
 *   - Subscription plan translation upsert
 *   - Multilingual metadata builder (for DTO enrichment)
 *   - AI translation integration points
 *
 * Architecture:
 *   Entity → Translation Layer → Language Variants
 *
 * One logical entity. Multiple localized variants.
 * No duplication of IDs, ownership, or relationships.
 */
import { getLogger } from "@/lib/logger";
import { badRequest, forbidden, notFound, unauthorized } from "@/lib/errors";
import { can, PersonalPermission, type AuthContext } from "@/features/rbac";
import { db } from "@/lib/db";
import { defaultLocale } from "@/i18n/routing";
import * as repo from "./repository";
import type {
  CategoryTranslationDto,
  MultilingualMetadata,
  PlanTranslationDto,
  ResourceTranslationDto,
  TranslationProvider,
  TranslationStatus,
} from "./types";

const log = getLogger("content-translation");

// ---------------------------------------------------------------------------
// Mappers
// ---------------------------------------------------------------------------

function safeParse<T>(raw: string | null, fallback: T): T {
  if (!raw) return fallback;
  try { return JSON.parse(raw) as T; } catch { return fallback; }
}

function mapResourceTranslation(t: any): ResourceTranslationDto {
  return {
    id: t.id,
    resourceId: t.resourceId,
    language: t.language,
    title: t.title,
    description: t.description,
    content: t.content,
    translationStatus: t.translationStatus as TranslationStatus,
    translatedBy: t.translatedBy,
    translationProvider: t.translationProvider as TranslationProvider | null,
    translationVersion: t.translationVersion,
    translatedAt: t.translatedAt ? t.translatedAt.toISOString() : null,
    isAutoGenerated: t.isAutoGenerated,
    slug: t.slug,
    createdAt: t.createdAt.toISOString(),
    updatedAt: t.updatedAt.toISOString(),
  };
}

function mapCategoryTranslation(t: any): CategoryTranslationDto {
  return {
    id: t.id,
    categoryId: t.categoryId,
    language: t.language,
    name: t.name,
    description: t.description,
    slug: t.slug,
    createdAt: t.createdAt.toISOString(),
    updatedAt: t.updatedAt.toISOString(),
  };
}

function mapPlanTranslation(t: any): PlanTranslationDto {
  return {
    id: t.id,
    planId: t.planId,
    language: t.language,
    name: t.name,
    description: t.description,
    features: safeParse(t.features, null),
    createdAt: t.createdAt.toISOString(),
    updatedAt: t.updatedAt.toISOString(),
  };
}

// ---------------------------------------------------------------------------
// Resource translation CRUD
// ---------------------------------------------------------------------------

export async function getResourceTranslations(
  ctx: AuthContext,
  resourceId: string,
): Promise<ResourceTranslationDto[]> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  const translations = await repo.findResourceTranslations(resourceId);
  return translations.map(mapResourceTranslation);
}

export async function getResourceTranslation(
  ctx: AuthContext,
  resourceId: string,
  language: string,
): Promise<ResourceTranslationDto> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  const translation = await repo.findResourceTranslation(resourceId, language);
  if (!translation) throw notFound("Translation not found");
  return mapResourceTranslation(translation);
}

export async function createResourceTranslation(
  ctx: AuthContext,
  resourceId: string,
  input: {
    language: string;
    title: string;
    description?: string;
    content?: string;
    translationStatus?: TranslationStatus;
    translationProvider?: TranslationProvider;
    isAutoGenerated?: boolean;
    slug?: string;
  },
): Promise<ResourceTranslationDto> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  // Verify resource exists and caller has access
  const resource = await db.resource.findUnique({
    where: { id: resourceId },
    select: { id: true, ownerId: true, title: true, language: true },
  });
  if (!resource) throw notFound("Resource not found");
  if (resource.ownerId !== ctx.userId && !ctx.isSuperadmin) {
    throw forbidden("Only the resource owner can create translations");
  }
  // Check if translation already exists
  const existing = await repo.findResourceTranslation(resourceId, input.language);
  if (existing) throw badRequest("Translation already exists for this language");

  const translation = await repo.createResourceTranslation({
    resourceId,
    language: input.language,
    title: input.title,
    description: input.description,
    content: input.content,
    translationStatus: input.translationStatus ?? "draft",
    translatedBy: input.isAutoGenerated ? undefined : ctx.userId,
    translationProvider: input.translationProvider,
    isAutoGenerated: input.isAutoGenerated ?? false,
    slug: input.slug,
  });

  log.info("translation.created", { resourceId, language: input.language });
  return mapResourceTranslation(translation);
}

export async function updateResourceTranslation(
  ctx: AuthContext,
  resourceId: string,
  language: string,
  input: {
    title?: string;
    description?: string | null;
    content?: string;
    translationStatus?: TranslationStatus;
    translationProvider?: TranslationProvider;
    translationVersion?: number;
    isAutoGenerated?: boolean;
    slug?: string | null;
  },
): Promise<ResourceTranslationDto> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  const resource = await db.resource.findUnique({
    where: { id: resourceId },
    select: { id: true, ownerId: true },
  });
  if (!resource) throw notFound("Resource not found");
  if (resource.ownerId !== ctx.userId && !ctx.isSuperadmin) {
    throw forbidden("Only the resource owner can update translations");
  }

  const updated = await repo.updateResourceTranslation(resourceId, language, {
    title: input.title,
    description: input.description,
    content: input.content,
    translationStatus: input.translationStatus,
    translationProvider: input.translationProvider,
    translationVersion: input.translationVersion,
    isAutoGenerated: input.isAutoGenerated,
    slug: input.slug,
  });

  return mapResourceTranslation(updated);
}

export async function deleteResourceTranslation(
  ctx: AuthContext,
  resourceId: string,
  language: string,
): Promise<{ resourceId: string; language: string }> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  const resource = await db.resource.findUnique({
    where: { id: resourceId },
    select: { id: true, ownerId: true, language: true },
  });
  if (!resource) throw notFound("Resource not found");
  if (resource.ownerId !== ctx.userId && !ctx.isSuperadmin) {
    throw forbidden("Only the resource owner can delete translations");
  }
  if (resource.language === language) {
    throw badRequest("Cannot delete the default language translation");
  }
  await repo.deleteResourceTranslation(resourceId, language);
  return { resourceId, language };
}

// ---------------------------------------------------------------------------
// Multilingual metadata builder
// ---------------------------------------------------------------------------

/**
 * Build multilingual metadata for a resource. This is the additive
 * enrichment that gets attached to resource DTOs so the frontend
 * knows what languages are available and what the translation state is.
 */
export async function buildMultilingualMetadata(
  resourceId: string,
  defaultLanguage: string,
  requestedLanguage?: string,
): Promise<MultilingualMetadata> {
  const translations = await repo.findResourceTranslations(resourceId);
  const availableLanguages = translations.map((t: any) => t.language);
  // Include the default language even if there's no explicit translation row
  if (!availableLanguages.includes(defaultLanguage)) {
    availableLanguages.unshift(defaultLanguage);
  }

  const currentLanguage = requestedLanguage ?? defaultLocale;
  const currentTranslation = translations.find(
    (t: any) => t.language === currentLanguage,
  );

  const isTranslated = currentLanguage !== defaultLanguage && !!currentTranslation;
  const translationStatus = currentTranslation
    ? (currentTranslation.translationStatus as TranslationStatus)
    : currentLanguage === defaultLanguage
      ? "published" as TranslationStatus
      : "missing" as TranslationStatus;

  return {
    defaultLanguage,
    availableLanguages,
    currentLanguage,
    isTranslated,
    translationStatus,
    canTranslate: true, // AI translation is always available
    translatedBy: currentTranslation?.translatedBy ?? null,
    translationProvider: (currentTranslation?.translationProvider as TranslationProvider) ?? null,
    translationVersion: currentTranslation?.translationVersion ?? 0,
    translatedAt: currentTranslation?.translatedAt
      ? currentTranslation.translatedAt.toISOString()
      : null,
  };
}

// ---------------------------------------------------------------------------
// Category translations
// ---------------------------------------------------------------------------

export async function getCategoryTranslations(
  ctx: AuthContext,
  categoryId: string,
): Promise<CategoryTranslationDto[]> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  const translations = await repo.findCategoryTranslations(categoryId);
  return translations.map(mapCategoryTranslation);
}

export async function upsertCategoryTranslation(
  ctx: AuthContext,
  categoryId: string,
  input: {
    language: string;
    name: string;
    description?: string;
    slug?: string;
  },
): Promise<CategoryTranslationDto> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  if (!can(ctx, PersonalPermission.RESOURCE_CREATE) && !ctx.isSuperadmin) {
    throw forbidden("No permission to manage category translations");
  }
  const result = await repo.upsertCategoryTranslation({
    categoryId,
    language: input.language,
    name: input.name,
    description: input.description,
    slug: input.slug,
  });
  return mapCategoryTranslation(result);
}

/**
 * Resolve a category's name for a specific locale.
 * Falls back to the default name if no translation exists.
 */
export async function resolveCategoryName(
  categoryId: string,
  locale: string,
): Promise<string> {
  const translation = await repo.findCategoryTranslation(categoryId, locale);
  if (translation) return translation.name;
  // Fallback to the category's default name
  const category = await db.mpCategory.findUnique({
    where: { id: categoryId },
    select: { name: true },
  });
  return category?.name ?? "Unknown";
}

// ---------------------------------------------------------------------------
// Subscription plan translations
// ---------------------------------------------------------------------------

export async function getPlanTranslations(
  ctx: AuthContext,
  planId: string,
): Promise<PlanTranslationDto[]> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  const translations = await repo.findPlanTranslations(planId);
  return translations.map(mapPlanTranslation);
}

export async function upsertPlanTranslation(
  ctx: AuthContext,
  planId: string,
  input: {
    language: string;
    name: string;
    description?: string;
    features?: Record<string, unknown>;
  },
): Promise<PlanTranslationDto> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  if (!can(ctx, PersonalPermission.SUBSCRIPTION_VIEW) && !ctx.isSuperadmin) {
    throw forbidden("No permission to manage plan translations");
  }
  const result = await repo.upsertPlanTranslation({
    planId,
    language: input.language,
    name: input.name,
    description: input.description,
    features: input.features ? JSON.stringify(input.features) : undefined,
  });
  return mapPlanTranslation(result);
}

/**
 * Resolve a plan's name for a specific locale.
 * Falls back to the default name if no translation exists.
 */
export async function resolvePlanName(
  planId: string,
  locale: string,
): Promise<string> {
  const translation = await repo.findPlanTranslation(planId, locale);
  if (translation) return translation.name;
  const plan = await db.subscriptionPlan.findUnique({
    where: { id: planId },
    select: { name: true },
  });
  return plan?.name ?? "Unknown";
}

// ---------------------------------------------------------------------------
// AI Translation integration
// ---------------------------------------------------------------------------

/**
 * Create an AI-generated translation for a resource.
 * This is the integration point for the AI translation pipeline.
 * The actual AI call is made by the caller; this function persists the result.
 */
export async function createAiTranslation(
  ctx: AuthContext,
  resourceId: string,
  language: string,
  translatedContent: {
    title: string;
    description?: string;
    content: string;
  },
): Promise<ResourceTranslationDto> {
  if (!ctx.userId) throw unauthorized("Authentication required");
  const resource = await db.resource.findUnique({
    where: { id: resourceId },
    select: { id: true, ownerId: true, language: true },
  });
  if (!resource) throw notFound("Resource not found");
  if (resource.ownerId !== ctx.userId && !ctx.isSuperadmin) {
    throw forbidden("Only the resource owner can create AI translations");
  }
  if (resource.language === language) {
    throw badRequest("Cannot translate to the same language as the original");
  }

  // Check if a translation already exists — if so, update it
  const existing = await repo.findResourceTranslation(resourceId, language);
  if (existing) {
    const updated = await repo.updateResourceTranslation(resourceId, language, {
      title: translatedContent.title,
      description: translatedContent.description,
      content: translatedContent.content,
      translationStatus: "published",
      translationProvider: "ai",
      translationVersion: existing.translationVersion + 1,
      isAutoGenerated: true,
    });
    log.info("ai_translation.updated", { resourceId, language, version: existing.translationVersion + 1 });
    return mapResourceTranslation(updated);
  }

  const translation = await repo.createResourceTranslation({
    resourceId,
    language,
    title: translatedContent.title,
    description: translatedContent.description,
    content: translatedContent.content,
    translationStatus: "published",
    translationProvider: "ai",
    isAutoGenerated: true,
  });

  log.info("ai_translation.created", { resourceId, language });
  return mapResourceTranslation(translation);
}
