/**
 * EduBek — Multilingual content translation types.
 *
 * Phase 4E.5: Universal translation model for all educational content.
 *
 * The translation layer pattern:
 *   Entity → Translation Layer → Language Variants
 *
 * One logical entity. Multiple localized variants.
 * No duplication of IDs, ownership, or relationships.
 */

/** Translation status lifecycle: draft → reviewing → approved → published → outdated */
export type TranslationStatus =
  | "draft"
  | "reviewing"
  | "approved"
  | "published"
  | "outdated"
  | "missing";

/** Who/what produced the translation. */
export type TranslationProvider = "ai" | "manual" | "google" | "deepl";

/** What kind of entity is being translated. */
export type TranslatableEntityType = "resource" | "category" | "subscription_plan";

/** A single language variant of a translatable entity. */
export interface ResourceTranslationDto {
  id: string;
  resourceId: string;
  language: string;
  title: string;
  description: string | null;
  content: string;
  translationStatus: TranslationStatus;
  translatedBy: string | null;
  translationProvider: TranslationProvider | null;
  translationVersion: number;
  translatedAt: string | null;
  isAutoGenerated: boolean;
  slug: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Category translation DTO. */
export interface CategoryTranslationDto {
  id: string;
  categoryId: string;
  language: string;
  name: string;
  description: string | null;
  slug: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Subscription plan translation DTO. */
export interface PlanTranslationDto {
  id: string;
  planId: string;
  language: string;
  name: string;
  description: string | null;
  features: Record<string, unknown> | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Multilingual metadata — additive fields exposed on every content DTO.
 * These let the frontend know what languages are available and what
 * the current translation state is.
 */
export interface MultilingualMetadata {
  /** The original language of the content (e.g. "en"). */
  defaultLanguage: string;
  /** All languages this content is available in (including the default). */
  availableLanguages: string[];
  /** The language of the current variant being served. */
  currentLanguage: string;
  /** Whether this content has been translated from its original language. */
  isTranslated: boolean;
  /** Current translation status of the requested language variant. */
  translationStatus: TranslationStatus;
  /** Whether AI translation is available for this content. */
  canTranslate: boolean;
  /** Who/what produced the translation (null for original content). */
  translatedBy: string | null;
  /** Translation provider used. */
  translationProvider: TranslationProvider | null;
  /** Translation version number. */
  translationVersion: number;
  /** When the translation was last updated. */
  translatedAt: string | null;
}

/** Default multilingual metadata for untranslated content. */
export function defaultMultilingualMetadata(language: string): MultilingualMetadata {
  return {
    defaultLanguage: language,
    availableLanguages: [language],
    currentLanguage: language,
    isTranslated: false,
    translationStatus: "published",
    canTranslate: true,
    translatedBy: null,
    translationProvider: null,
    translationVersion: 0,
    translatedAt: null,
  };
}
