/** Platform SDK, Extension & Plugin Framework service — composes all 24 systems. Phase 6G.27. */
export {
  registerExtension, getExtensionById, getExtensionByKeyOrSlug, listExtensions,
  activateExtension, disableExtension, suspendExtension, removeExtension,
  setExtensionVersion, linkExtensionManifest, linkExtensionSdk, publishExtensionToMarketplace,
  supportsAllExtensionStatuses, supportsAllExtensionVisibilities,
  registerPlugin, getPluginById, listPlugins,
  submitPlugin, approvePlugin, rejectPlugin, archivePlugin,
  incrementPluginDownloads, ratePlugin,
  supportsAllPluginStatuses, supportsAllPluginCategories,
  createManifest, getManifestById, getManifestForExtension, listManifests, updateManifest,
  addManifestPermission, addManifestHook, addManifestDependency, addManifestEntryPoint,
  supportsAllHookTypes, supportsAllEntryPointTypes,
  registerSdk, getSdkById, listSdks, publishSdk, deprecateSdk, retireSdk, addSdkSupportedApi,
  supportsAllSdkStatuses, supportsAllSdkLanguages,
  registerCapability, getCapabilityById, listCapabilities, restrictCapability, deprecateCapability,
  supportsAllCapabilityScopes, supportsAllCapabilityStatuses,
  registerHook, getHookById, listHooks, setHookActive, setHookPriority,
  registerPermissionDef, getPermissionDefById, listPermissionDefs,
  requestPermission, getPermissionGrantById, listPermissionGrants,
  approvePermission, denyPermission, revokePermission, expirePermission,
  supportsAllPermissionStatuses, supportsAllPermissionCategories,
  createSandboxPolicy, getSandboxPolicyById, getSandboxPolicyForExtension, listSandboxPolicies,
  updateSandboxHealth, setNetworkAllowlist,
  supportsAllNetworkPolicies, supportsAllSandboxHealthStatuses,
  recordCompatibility, getCompatibilityById, listCompatibility, findCompatibility,
  supportsAllCompatibilityVerdicts, compareVersions,
  evaluateDependencies, getDependencyNodeById, getDependencyNodeForExtension, listDependencyNodes,
  matchesVersionRange, supportsAllDependencyResolutions,
  recordLifecycle, getLifecycleRecordById, listLifecycleRecords, getLatestLifecycleState,
  supportsAllLifecycleStates, supportsAllLifecycleTransitions, isValidTransition,
  createMarketplaceListing, getMarketplaceListingById, getMarketplaceListingForExtension,
  listMarketplaceListings, publishMarketplaceListing, unlistMarketplaceListing,
  rejectMarketplaceListing, delistMarketplaceListing,
  updateMarketplaceRating, incrementMarketplaceInstalls, decrementMarketplaceInstalls,
  supportsAllMarketplaceListingStatuses,
} from "./core";
export {
  createConfig, getConfigById, getConfigForExtension, listConfigs,
  updateConfigSettings, addConfigSecret, addConfigOverride, supportsAllConfigScopes,
  createEventSubscription, getEventSubscriptionById, listEventSubscriptions,
  setEventSubscriptionActive, registerEventContract, getEventContractById,
  listEventContracts, supportsAllEventDirections,
  createApiContract, getApiContractById, listApiContracts, deprecateApiContract,
  supportsAllApiScopes, supportsAllApiStabilities,
  upsertDeveloperPortalMetadata, getDeveloperPortalMetadataById,
  getDeveloperPortalMetadataForExtension, listDeveloperPortalMetadata, syncDeveloperPortalMetadata,
  runValidation, getValidationReportById, listValidationReports,
  validateManifestStructure, supportsAllValidationSeverities, supportsAllValidationKinds,
  recordAudit, getAuditRecordById, listAuditRecords,
  supportsAllAuditCategories, supportsAllAuditOutcomes,
  generateExtensionAnalytics,
  generateExtensionDashboard,
  getDeveloperIntegration, getExtensionFrameworkStatus,
  generateDocumentation, generateMarkdownDocumentation, getExtensionFrameworkVersion,
} from "./platform";
export {
  subscribeExtensionFramework, unsubscribeExtensionFramework, isExtensionFrameworkSubscribed,
  getBridgeProcessedCount, getBridgePublishedCount, getPublishedEvents,
  publishExtensionEvent, _resetBridgeForTesting,
} from "./event-bus-bridge";
export { _resetRepositoryForTesting } from "./repository";
export type {
  ExtensionStatus, ExtensionVisibility, ExtensionRegistryEntry,
  PluginStatus, PluginCategory, PluginRegistryEntry,
  HookType, EntryPointType,
  ManifestPermissionRef, ManifestHookRef, ManifestDependencyRef, ManifestEntryPoint, ExtensionManifest,
  SdkStatus, SdkLanguage, SdkEntry,
  CapabilityScope, CapabilityStatus, CapabilityEntry,
  HookEntry,
  PermissionStatus, PermissionCategory, ExtensionPermission, PermissionGrant,
  NetworkPolicy, SandboxHealthStatus, SandboxPolicy,
  CompatibilityVerdict, CompatibilityEntry,
  DependencyResolution, DependencyNode,
  LifecycleState, LifecycleTransition, LifecycleRecord,
  MarketplaceListingStatus, MarketplaceListing,
  ConfigScope, ExtensionConfig,
  EventDirection, EventSubscription, EventContract,
  ApiScope, ApiStability, ApiContract,
  DeveloperPortalMetadata,
  ValidationSeverity, ValidationKind, ValidationIssue, ValidationReport,
  AuditCategory, AuditOutcome, AuditRecord,
  ExtensionAnalytics, ExtensionDashboard,
  ExtensionFrameworkEventType,
  ExtensionDeveloperIntegration, ExtensionAdminStatus, ExtensionDocumentation,
} from "./types";
