/** AI Intelligence Platform service — composes all 24 systems. Phase 6G.26. */
export {
  registerModel, getModelById, listModels, activateModel, deprecateModel,
  supportsAllModelTypes, supportsAllModelStatuses,
  createPrompt, getPromptById, listPrompts, activatePrompt, supportsAllPromptStatuses,
  registerEmbedding, getEmbeddingById, listEmbeddings,
  createFeatureDef, getFeatureDefById, listFeatureDefs, storeFeatureVectorForEntity, getFeatureVectorsForEntity, supportsAllFeatureDataTypes,
  generateRecommendation, getRecommendationById, listRecommendations, serveRecommendation, clickRecommendation, dismissRecommendation, supportsAllRecommendationStatuses,
  createPersonalization, getPersonalizationForUser, listPersonalizations, updatePersonalization, optOutPersonalization, supportsAllPersonalizationStatuses,
  createRankingProfile, getRankingProfileById, listRankingProfiles, supportsAllRankingStrategies,
  buildContext, getContextById, listContexts,
  createExperiment, getExperimentById, listExperiments, startExperiment, completeExperiment, supportsAllExperimentStatuses,
  createEvaluation, getEvaluationById, listEvaluations, completeEvaluation, supportsAllEvalStatuses,
  publishPromptVersion, getPromptVersionHistory, getActivePromptVersion,
  createInference, getInferenceById, listInferences, completeInference, failInference, supportsAllInferenceStatuses,
} from "./core";
export {
  createPolicy, getPolicyById, listPolicies, supportsAllPolicyEnforcements,
  createGuardrailRule, getGuardrailRuleById, listGuardrailRules, triggerGuardrail, listGuardrailTriggers,
  supportsAllGuardrailSeverities, supportsAllGuardrailActions,
  createReviewItem, getReviewItemById, listReviewItems, approveReviewItem, rejectReviewItem, supportsAllReviewStatuses,
  recordFeedback, listFeedback, supportsAllFeedbackTypes,
  generateAIAnalytics,
  recordCost, generateCostSummary, listCostRecords,
  createGovernance, getGovernanceById, listGovernance, approveGovernance, rejectGovernance, supportsAllGovernanceStatuses,
  generateAIDashboard,
  getDeveloperIntegration, getAIStatus,
  generateDocumentation, generateMarkdownDocumentation, getAIVersion,
} from "./platform";
export {
  subscribeAIIntelligence, unsubscribeAIIntelligence, isAIIntelligenceSubscribed,
  getBridgeProcessedCount, getBridgePublishedCount, getPublishedEvents,
  publishAIEvent, _resetBridgeForTesting,
} from "./event-bus-bridge";
export { _resetRepositoryForTesting } from "./repository";
export type {
  ModelType, ModelStatus, AIModel,
  PromptStatus, PromptTemplate,
  EmbeddingModelMeta,
  FeatureDataType, FeatureDefinition, FeatureVector,
  RecommendationStatus, Recommendation,
  PersonalizationStatus, PersonalizationProfile,
  RankingStrategy, RankingProfile,
  AIContext,
  ExperimentStatus, Experiment,
  EvalStatus, EvaluationResult,
  PromptVersion,
  InferenceStatus, InferenceRequest,
  PolicyEnforcement, AIPolicy,
  GuardrailSeverity, GuardrailAction, GuardrailRule, GuardrailTrigger,
  ReviewStatus, ReviewItem,
  FeedbackType, AIFeedback,
  AIAnalytics, CostRecord, CostSummary,
  GovernanceStatus, AIGovernanceRecord,
  AIDashboard, AIIntelligenceEventType,
  AIDeveloperIntegration, AIAdminStatus, AIDocumentation,
} from "./types";
