export const PLATFORM_CONFIG = {
  MARKETPLACE_PLATFORM_FEE_PERCENT: 10,
  REFUND_WINDOW_DAYS: 7,
  ALLOW_DUPLICATE_PURCHASES: false,
  PLATFORM_WALLET_USER_ID: process.env.PLATFORM_WALLET_USER_ID ?? 'platform',
} as const
