/** Cosmetics Platform service — composes all 16 systems. */
export { initializeRarities, getRarityDefinition, listRarities, DEFAULT_RARITIES } from "./catalog-equipment";
export { createCosmetic, getCosmeticById, listCosmetics, createLoadout, getLoadoutsForUser, getLoadoutById, equipItem, unequipItem, detectConflicts, isValidSlotForCosmetic, EQUIPMENT_SLOTS } from "./catalog-equipment";
export { grantItem, revokeItem, giftItem, consumeItem, expireItem, restoreItem, hideItem, getInventory, getOwnedItems, getEquippedItems, getExpiredItems, getTemporaryItems, getTransactionHistory, registerUnlockCondition, getUnlockConditionsForCosmetic, checkUnlockConditions } from "./inventory-transactions";
export { initIdentity, getIdentityForUser, updateIdentity, setAvatar, setFrame, setBanner, setTheme, setBackground, setTitle, addBadge, removeBadge, updatePublicCard, initShowcase, getShowcaseForUser, addFeaturedCosmetic, removeFeaturedCosmetic, addFeaturedCollection, addFeaturedAchievement, addFeaturedStat } from "./identity-showcase";
export { createCollection, getCollectionById, listCollections, computeCollectionProgress, getUserCollections, initPersonalization, getPersonalizationForUser, updatePersonalization, setTheme as setPersonalizationTheme, setAccessibilityTheme, setAnimationPack, setSoundPack, setUIScale, setReducedMotion, setHighContrast, setColorBlindMode, registerSeasonalCosmetic, getSeasonalInfo, listSeasonalCosmetics, retireSeasonalCosmetic, isSeasonalAvailable, createOrgIdentity, getOrgIdentityById, listOrgIdentities, updateOrgIdentity } from "./collections-personalization";
export { registerMarketplaceItem, getMarketplaceInfo, listMarketplaceItems, verifyLicense, recordPurchase, registerExtensionCosmetic, getExtensionInfo, validateExtensionCosmetic, generateAnalytics, generateDashboard, getDeveloperIntegration } from "./marketplace-extensions-analytics";
export { subscribeCosmetics, unsubscribeCosmetics, isCosmeticsSubscribed, getBridgeProcessedCount, publishCosmeticEvent, _resetBridgeForTesting } from "./event-bus-bridge";
export { _resetRepositoryForTesting } from "./repository";
