import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
const ROOT = process.cwd();
const KEYS = {
  en: { title: "Treasure Heist", description: "Strategic risk economy game mode.",
    rules: { startingGold: "Starting Gold: {value}", questionReward: "Reward: {value}", investOdds: "Invest Success: {value}%", stealOdds: "Steal Success: {value}%", rounds: "Rounds: {value}", questions: "Questions: {value}", timer: "Timer: {value}s", decisionTime: "Decision Time: {value}s" },
    economy: { gold: "Gold", balance: "Balance: {value}", earned: "Earned {value} gold", lost: "Lost {value} gold", stolen: "Stolen {value} gold", bonus: "Bonus: {value} gold", penalty: "Penalty: -{value} gold" },
    decisions: { save: "SAVE", invest: "INVEST", steal: "STEAL", saveDesc: "Keep your gold safe", investDesc: "Double or nothing", stealDesc: "Take from others", timeout: "Decision timed out!", window: "Choose: Save, Invest, or Steal?" },
    invest: { success: "Investment succeeded! +{value} gold", failure: "Investment failed! -{value} gold", multiplier: "Multiplier: x{value}" },
    steal: { success: "Stole {value} gold!", failure: "Steal failed! Penalty: -{value}", shielded: "Target has a shield!", noSteals: "No steals remaining!" },
    protection: { shield: "Shield Active", shieldExpired: "Shield Expired", cooldown: "Steal Cooldown", teacherProtect: "Teacher Protection Active", remaining: "Steals remaining: {value}" },
    events: { golden_chest: "Golden Chest!", treasure_map: "Treasure Map!", lucky_coin: "Lucky Coin!", bandits: "Bandits!", storm: "Storm!", trap: "Trap!", secret_vault: "Secret Vault!", tax_collector: "Tax Collector!", merchant: "Merchant!", treasure_hunter: "Treasure Hunter!" },
    leaderboard: { gold: "Gold Ranking", net_worth: "Net Worth", steals: "Most Steals", investments: "Best Investor", accuracy: "Accuracy", speed: "Fastest", correct: "Most Correct", efficiency: "Efficiency", final: "Final Ranking" },
    achievements: { safe_investor: "Safe Investor", master_thief: "Master Thief", treasure_king: "Treasure King", lucky_player: "Lucky Player", risk_master: "Risk Master", perfect_investor: "Perfect Investor", gold_hoarder: "Gold Hoarder", untouchable: "Untouchable", smart_economist: "Smart Economist", comeback: "Comeback" },
    teacher: { pause: "Pause", resume: "Resume", skip: "Skip", freeze: "Freeze Decisions", inject: "Inject Event", protect: "Protect Player", bonus: "Give Bonus", deduct: "Deduct Gold", reset: "Reset Economy", reveal: "Reveal Economy", hide: "Hide Economy", end: "End Match", emergency: "Emergency Stop" },
    student: { waiting: "Waiting", question: "Question", answering: "Answering", correct: "Correct!", wrong: "Wrong!", decision: "Decision Time", saving: "Saving...", investing: "Investing...", stealing: "Stealing...", event: "Event!", leaderboard: "Leaderboard", summary: "Match Summary", disconnected: "Disconnected", reconnecting: "Reconnecting..." },
    summary: { winner: "Winner: {name}", topPlayers: "Top Players", economyTimeline: "Economy Timeline", investments: "Investment Stats", steals: "Steal Stats", decisions: "Decision Distribution", accuracy: "Avg Accuracy: {value}%", fastest: "Fastest: {name}", replay: "Replay Available", export: "Export Available" },
    analytics: { avgGold: "Avg Gold: {value}", totalGold: "Total Gold: {value}", inflation: "Inflation: {value}%", saveRate: "Save: {value}%", investRate: "Invest: {value}%", stealRate: "Steal: {value}%", stealSuccess: "Steal Success: {value}%", investSuccess: "Invest Success: {value}%", dropouts: "Dropouts: {value}", reconnects: "Reconnects: {value}" },
    dashboard: { economy: "Economy Graph", leaders: "Current Leaders", decisionTimer: "Decision Timer", pending: "Pending Decisions: {value}", activeEvents: "Active Events", recentSteals: "Recent Steals", recentInvestments: "Recent Investments", interventions: "Interventions: {value}", health: "Match Health: {value}", latency: "Latency: {value}ms", connected: "Connected: {value}", disconnected: "Disconnected: {value}" },
    accessibility: { keyboard: "Keyboard Nav", motion: "Reduced Motion", contrast: "High Contrast", reader: "Screen Reader", largeText: "Large Text", colorBlind: "Color Blind Friendly", audio: "Audio Cues", timer: "Timer Accessibility" },
  },
  uz: { title: "Treasure Heist", description: "Strategik risk iqtisodiyoti o'yin rejimi.",
    rules: { startingGold: "Boshlang'ich oltin: {value}", questionReward: "Mukofot: {value}", investOdds: "Investitsiya muvaffaqiyati: {value}%", stealOdds: "O'g'rilik muvaffaqiyati: {value}%", rounds: "Raundlar: {value}", questions: "Savollar: {value}", timer: "Taymer: {value}s", decisionTime: "Qaror vaqti: {value}s" },
    economy: { gold: "Oltin", balance: "Balans: {value}", earned: "{value} oltin ishlandi", lost: "{value} oltin yo'qoldi", stolen: "{value} oltin o'g'irlandi", bonus: "Bonus: {value} oltin", penalty: "Jarima: -{value} oltin" },
    decisions: { save: "SAQLASH", invest: "INVESTITSIYA", steal: "O'G'IRLASH", saveDesc: "Oltinni saqlang", investDesc: "Ikki barobar yoki hech narsa", stealDesc: "Boshqalardan oling", timeout: "Qaror vaqti tugadi!", window: "Tanlang: Saqlash, Investitsiya, yoki O'g'rilash?" },
    invest: { success: "Investitsiya muvaffaqiyatli! +{value} oltin", failure: "Investitsiya xato! -{value} oltin", multiplier: "Ko'paytuvchi: x{value}" },
    steal: { success: "{value} oltin o'g'irlandi!", failure: "O'g'rilik xato! Jarima: -{value}", shielded: "Nishonda himoya bor!", noSteals: "O'g'riliklar tugadi!" },
    protection: { shield: "Himoya faol", shieldExpired: "Himoya tugadi", cooldown: "O'g'rilik kutish", teacherProtect: "O'qituvchi himoyasi faol", remaining: "Qolgan o'g'riliklar: {value}" },
    events: { golden_chest: "Oltin sandiq!", treasure_map: "Xazina xaritasi!", lucky_coin: "Ommonli tanga!", bandits: "Qaroqchilar!", storm: "Bo'ron!", trap: "Tuzoq!", secret_vault: "Maxfiy seyf!", tax_collector: "Soliq yig'uvchi!", merchant: "Sotuvchi!", treasure_hunter: "Xazina ovchisi!" },
    leaderboard: { gold: "Oltin reytingi", net_worth: "Umumiy qiymat", steals: "Eng ko'p o'g'rilik", investments: "Eng yaxshi investor", accuracy: "Aniqlik", speed: "Eng tez", correct: "Eng ko'p to'g'ri", efficiency: "Samaradorlik", final: "Yakuniy reyting" },
    achievements: { safe_investor: "Xavfsiz Investor", master_thief: "Usta O'g'ri", treasure_king: "Xazina Shohi", lucky_player: "Omonli O'yinchi", risk_master: "Risk Ustasi", perfect_investor: "Mukammal Investor", gold_hoarder: "Oltin Yig'uvchi", untouchable: "Etilmas", smart_economist: "Aqlli Iqtisodchi", comeback: "Qaytish" },
    teacher: { pause: "To'xtatish", resume: "Davom", skip: "O'tkazib yuborish", freeze: "Qarorlarni muzlatish", inject: "Hodisa qo'shish", protect: "O'yinchini himoya qilish", bonus: "Bonus berish", deduct: "Oltin ayirish", reset: "Iqtisodiyotni tiklash", reveal: "Iqtisodiyotni ko'rsatish", hide: "Iqtisodiyotni yashirish", end: "O'yinni tugatish", emergency: "Favqulodda to'xtash" },
    student: { waiting: "Kutmoqda", question: "Savol", answering: "Javob berilmoqda", correct: "To'g'ri!", wrong: "Noto'g'ri!", decision: "Qaror vaqti", saving: "Saqlanmoqda...", investing: "Investitsiya...", stealing: "O'g'rilash...", event: "Hodisa!", leaderboard: "Reyting", summary: "O'yin yakuni", disconnected: "Uzilgan", reconnecting: "Qayta ulanmoqda..." },
    summary: { winner: "G'olib: {name}", topPlayers: "Top o'yinchilar", economyTimeline: "Iqtisodiyot vaqt chizig'i", investments: "Investitsiya statistikasi", steals: "O'g'rilik statistikasi", decisions: "Qaror taqsimoti", accuracy: "O'rtacha aniqlik: {value}%", fastest: "Eng tez: {name}", replay: "Replay mavjud", export: "Eksport mavjud" },
    analytics: { avgGold: "O'rtacha oltin: {value}", totalGold: "Jami oltin: {value}", inflation: "Inflyatsiya: {value}%", saveRate: "Saqlash: {value}%", investRate: "Investitsiya: {value}%", stealRate: "O'g'rilik: {value}%", stealSuccess: "O'g'rilik muvaffaqiyati: {value}%", investSuccess: "Investitsiya muvaffaqiyati: {value}%", dropouts: "Tark etganlar: {value}", reconnects: "Qayta ulanishlar: {value}" },
    dashboard: { economy: "Iqtisodiyot grafigi", leaders: "Joriy liderlar", decisionTimer: "Qaror taymeri", pending: "Kutilayotgan qarorlar: {value}", activeEvents: "Faol hodisalar", recentSteals: "So'nggi o'g'riliklar", recentInvestments: "So'nggi investitsiyalar", interventions: "Aralashuvlar: {value}", health: "O'yin holati: {value}", latency: "Kechikish: {value}ms", connected: "Ulangan: {value}", disconnected: "Uzilgan: {value}" },
    accessibility: { keyboard: "Klaviatura navigatsiyasi", motion: "Kamaytirilgan harakat", contrast: "Yuqori kontrast", reader: "Ekran o'qigich", largeText: "Katta matn", colorBlind: "Rang ko'r uchun", audio: "Audio signallar", timer: "Taymer uchun" },
  },
  ru: { title: "Охота за Сокровищами", description: "Стратегический игровой режим с экономикой риска.",
    rules: { startingGold: "Стартовое золото: {value}", questionReward: "Награда: {value}", investOdds: "Успех инвестиции: {value}%", stealOdds: "Успех кражи: {value}%", rounds: "Раундов: {value}", questions: "Вопросов: {value}", timer: "Таймер: {value}с", decisionTime: "Время решения: {value}с" },
    economy: { gold: "Золото", balance: "Баланс: {value}", earned: "Получено {value} золота", lost: "Потеряно {value} золота", stolen: "Украдено {value} золота", bonus: "Бонус: {value} золота", penalty: "Штраф: -{value} золота" },
    decisions: { save: "СОХРАНИТЬ", invest: "ИНВЕСТИРОВАТЬ", steal: "УКРАСТЬ", saveDesc: "Сохранить золото", investDesc: "Удвоить или потерять", stealDesc: "Забрать у других", timeout: "Время решения истекло!", window: "Выберите: Сохранить, Инвестировать или Украсть?" },
    invest: { success: "Инвестиция успешна! +{value} золота", failure: "Инвестиция провалена! -{value} золота", multiplier: "Множитель: x{value}" },
    steal: { success: "Украдено {value} золота!", failure: "Кража провалена! Штраф: -{value}", shielded: "У цели есть щит!", noSteals: "Кражи закончились!" },
    protection: { shield: "Щит активен", shieldExpired: "Щит истёк", cooldown: "Перезарядка кражи", teacherProtect: "Защита учителя активна", remaining: "Осталось краж: {value}" },
    events: { golden_chest: "Золотой сундук!", treasure_map: "Карта сокровищ!", lucky_coin: "Счастливая монета!", bandits: "Разбойники!", storm: "Шторм!", trap: "Ловушка!", secret_vault: "Тайный сейф!", tax_collector: "Сборщик налогов!", merchant: "Торговец!", treasure_hunter: "Охотник за сокровищами!" },
    leaderboard: { gold: "Рейтинг по золоту", net_worth: "Чистая стоимость", steals: "Больше всего краж", investments: "Лучший инвестор", accuracy: "Точность", speed: "Самый быстрый", correct: "Больше всего правильных", efficiency: "Эффективность", final: "Итоговый рейтинг" },
    achievements: { safe_investor: "Осторожный Инвестор", master_thief: "Мастер Вор", treasure_king: "Король Сокровищ", lucky_player: "Везунчик", risk_master: "Мастер Риска", perfect_investor: "Идеальный Инвестор", gold_hoarder: "Копитель Золота", untouchable: "Неприкасаемый", smart_economist: "Умный Экономист", comeback: "Возвращение" },
    teacher: { pause: "Пауза", resume: "Продолжить", skip: "Пропустить", freeze: "Заморозить решения", inject: "Внедрить событие", protect: "Защитить игрока", bonus: "Дать бонус", deduct: "Списать золото", reset: "Сбросить экономику", reveal: "Показать экономику", hide: "Скрыть экономику", end: "Завершить матч", emergency: "Экстренная остановка" },
    student: { waiting: "Ожидание", question: "Вопрос", answering: "Ответ", correct: "Верно!", wrong: "Неверно!", decision: "Время решения", saving: "Сохранение...", investing: "Инвестирование...", stealing: "Кража...", event: "Событие!", leaderboard: "Таблица лидеров", summary: "Итоги матча", disconnected: "Отключён", reconnecting: "Переподключение..." },
    summary: { winner: "Победитель: {name}", topPlayers: "Лучшие игроки", economyTimeline: "График экономики", investments: "Статистика инвестиций", steals: "Статистика краж", decisions: "Распределение решений", accuracy: "Средняя точность: {value}%", fastest: "Самый быстрый: {name}", replay: "Повтор доступен", export: "Экспорт доступен" },
    analytics: { avgGold: "Среднее золото: {value}", totalGold: "Всего золота: {value}", inflation: "Инфляция: {value}%", saveRate: "Сохранение: {value}%", investRate: "Инвестиции: {value}%", stealRate: "Кражи: {value}%", stealSuccess: "Успех краж: {value}%", investSuccess: "Успех инвестиций: {value}%", dropouts: "Выбыло: {value}", reconnects: "Переподключений: {value}" },
    dashboard: { economy: "График экономики", leaders: "Текущие лидеры", decisionTimer: "Таймер решений", pending: "Ожидают решения: {value}", activeEvents: "Активные события", recentSteals: "Недавние кражи", recentInvestments: "Недавние инвестиции", interventions: "Вмешательств: {value}", health: "Состояние матча: {value}", latency: "Задержка: {value}мс", connected: "Подключено: {value}", disconnected: "Отключено: {value}" },
    accessibility: { keyboard: "Клавиатурная навигация", motion: "Уменьшенное движение", contrast: "Высокий контраст", reader: "Экранный чтец", largeText: "Крупный текст", colorBlind: "Для дальтоников", audio: "Звуковые сигналы", timer: "Доступность таймера" },
  },
} as const;
for (const locale of ["en", "uz", "ru"] as const) {
  const filePath = join(ROOT, "messages", `${locale}.json`);
  const content = JSON.parse(readFileSync(filePath, "utf-8")) as Record<string, unknown>;
  content.treasureHeist = KEYS[locale];
  writeFileSync(filePath, JSON.stringify(content, null, 2) + "\n", "utf-8");
  console.log(`Added treasureHeist keys to ${locale}.json`);
}
