/**
 * Quiz feature — domain types.
 *
 * These are the DTOs (Data Transfer Objects) returned by the quiz service.
 * They are framework-agnostic (no Prisma types, no Next.js types) so they
 * can be used by API routes, Server Components, and client components alike.
 *
 * Prisma model types never leak out of the repository layer.
 */

export type Difficulty = 'easy' | 'medium' | 'hard'

/**
 * Optional image attached to a question.
 *
 * MVP scope (Phase MVP-Quiz-Image):
 *   - Single optional image per question. No audio, no video, no galleries,
 *     no annotations.
 *   - Only the image reference (URL or storage path) is stored — the
 *     existing storage approach is reused. No new binary storage pipeline.
 *   - `alt` is optional but recommended for accessibility.
 *
 * Future evolution (intentionally NOT implemented today):
 *   - The shape is a discriminated union candidate: future media kinds
 *     (audio, video, …) can be added as sibling optional fields without
 *     breaking existing clients. Clients MUST treat unknown media fields
 *     as "no media" rather than failing.
 */
export interface QuestionMedia {
  /** Image URL or internal storage path (e.g. `/uploads/<cuid>.png`). */
  imageUrl: string
  /** Optional accessibility/alt text. */
  alt?: string | null
}

/**
 * A question that can be played in the QuizPlayer component.
 * Works for both DB-backed questions (QuizQuestionDto) and AI-generated
 * questions (AiQuizQuestionDto) — both satisfy this interface via
 * TypeScript's structural typing.
 *
 * `id` is optional: DB-backed questions have one, AI-generated questions
 * don't (the player falls back to the array index for React keys).
 *
 * `media` is optional: when absent, the question renders text-only exactly
 * like before.
 */
export interface PlayableQuestion {
  id?: string
  question: string
  options: string[]
  correctIndex: number
  explanation?: string | null
  /** Optional single image attachment. */
  media?: QuestionMedia | null
}

export interface QuizCreatorDto {
  id: string
  name: string
  username: string | null
  verificationStatus: string
  avatarInitials: string
}

export interface QuizQuestionDto {
  id: string
  question: string
  options: string[]
  correctIndex: number
  explanation: string | null
  orderNum: number
  /** Optional single image attachment (mapped from Prisma `Question.mediaUrl`). */
  media: QuestionMedia | null
}

/** Full quiz detail — returned by GET /api/quiz/[id]. */
export interface QuizDetailDto {
  id: string
  title: string
  description: string | null
  category: string
  difficulty: string
  language: string
  questionCount: number
  /** Whether the quiz was generated by the AI Quiz Generator. */
  isAiGenerated: boolean
  creator: QuizCreatorDto
  questions: QuizQuestionDto[]
}
