import { z } from 'zod'
export const createListingBodySchema = z.object({ resourceId: z.string().min(1), title: z.string().min(1).max(200), description: z.string().max(2000).optional(), thumbnailUrl: z.string().url().optional(), estimatedDuration: z.string().max(50).optional(), difficulty: z.enum(['easy', 'medium', 'hard', 'expert']).optional(), price: z.number().min(0).default(0), currency: z.string().min(3).max(3).default('USD'), licenseType: z.enum(['personal', 'classroom', 'org']).default('personal'), categoryIds: z.array(z.string()).max(5).default([]), orgId: z.string().optional() })
export type CreateListingBody = z.infer<typeof createListingBodySchema>
export const updateListingBodySchema = z.object({ title: z.string().min(1).max(200).optional(), description: z.string().max(2000).nullable().optional(), thumbnailUrl: z.string().url().nullable().optional(), estimatedDuration: z.string().max(50).nullable().optional(), difficulty: z.enum(['easy', 'medium', 'hard', 'expert']).nullable().optional(), price: z.number().min(0).optional(), currency: z.string().min(3).max(3).optional(), licenseType: z.enum(['personal', 'classroom', 'org']).optional(), featured: z.boolean().optional(), categoryIds: z.array(z.string()).max(5).optional() })
export type UpdateListingBody = z.infer<typeof updateListingBodySchema>
export const browseListingsQuerySchema = z.object({ search: z.string().optional(), resourceType: z.string().optional(), grade: z.string().optional(), subject: z.string().optional(), language: z.string().optional(), creatorId: z.string().optional(), categoryId: z.string().optional(), featured: z.boolean().optional(), free: z.boolean().optional(), paid: z.boolean().optional(), sort: z.enum(['newest', 'popular', 'featured', 'rated', 'alphabetical']).default('newest'), limit: z.coerce.number().int().min(1).max(100).default(20), offset: z.coerce.number().int().min(0).default(0) })
export type BrowseListingsQuery = z.infer<typeof browseListingsQuerySchema>
export const createCategoryBodySchema = z.object({ slug: z.string().min(2).max(50).regex(/^[a-z0-9-]+$/), name: z.string().min(2).max(100), description: z.string().max(500).optional(), icon: z.string().max(10).optional(), sortOrder: z.number().int().default(0) })
export type CreateCategoryBody = z.infer<typeof createCategoryBodySchema>
