/** Multi-Tenant Organization, Institution & Workspace Platform service — composes all 25 systems. Phase 6G.28. */
export {
  registerOrganization, getOrganizationById, getOrganizationByKeyOrSlug, listOrganizations,
  updateOrganization, setOrganizationStatus,
  supportsAllOrganizationStatuses, supportsAllOrganizationTypes,
  createTenant, getTenantById, listTenants, activateTenant, suspendTenant, archiveTenant,
  setTenantRootOrganization, supportsAllTenantStatuses,
  registerInstitutionType, getInstitutionTypeById, listInstitutionTypes, deactivateInstitutionType,
  registerHierarchyNode, getHierarchyNodeById, getHierarchyForOrganization, listHierarchyNodes,
  getChildren, getDescendants, moveOrganization, listHierarchyUpdates,
  createCampus, getCampusById, listCampuses, setCampusStatus, supportsAllCampusStatuses,
  createDepartment, getDepartmentById, listDepartments, setDepartmentStatus, supportsAllDepartmentStatuses,
  createFaculty, getFacultyById, listFaculties, setFacultyStatus, addFacultyDepartment, supportsAllFacultyStatuses,
  createWorkspace, getWorkspaceById, listWorkspaces, archiveWorkspace,
  supportsAllWorkspaceTypes, supportsAllWorkspaceStatuses,
  addMembership, getMembershipById, listMemberships, setMembershipStatus, setMembershipRole,
  supportsAllMembershipRoles, supportsAllMembershipStatuses,
  createInvitation, getInvitationById, getInvitationByTokenString, listInvitations,
  acceptInvitation, rejectInvitation, withdrawInvitation, expireInvitation,
  supportsAllInvitationStatuses,
  setBranding, getBrandingById, getBrandingForOrganization, listBranding,
  createConfig, getConfigById, getConfigForOrganization, listConfigs,
  updateConfigSettings, addConfigSecret, addConfigOverride, supportsAllConfigScopes,
} from "./core";
export {
  createPolicy, getPolicyById, listPolicies, updatePolicyEnforcement, deactivatePolicy,
  supportsAllPolicyEnforcements,
  recordLifecycle, getLifecycleRecordById, listLifecycleRecords, getLatestLifecycleStatus,
  supportsAllLifecycleTransitions,
  assignLicense, getLicenseById, listLicenses, suspendLicense, revokeLicense, expireLicense,
  incrementLicenseSeats, supportsAllLicenseStatuses,
  setQuota, getQuotaById, listQuotas, incrementQuotaUsed,
  supportsAllQuotaResources, supportsAllQuotaStatuses,
  registerDomain, getDomainById, listDomains, startDomainVerification, verifyDomain,
  failDomainVerification, revokeDomain, supportsAllDomainStatuses,
  setTenantIsolation, getIsolationById, getIsolationForTenant, listIsolations,
  supportsAllIsolationBoundaries,
  generateOrganizationAnalytics,
  recordAudit, getAuditRecordById, listAuditRecords,
  supportsAllAuditCategories, supportsAllAuditOutcomes,
  generateOrganizationDashboard,
  getDeveloperIntegration, getOrganizationPlatformStatus,
} from "./platform";
export {
  generateDocumentation, generateMarkdownDocumentation, getOrganizationPlatformVersion,
} from "./documentation";
export {
  subscribeOrganizationPlatform, unsubscribeOrganizationPlatform, isOrganizationPlatformSubscribed,
  getBridgeProcessedCount, getBridgePublishedCount, getPublishedEvents,
  publishOrganizationEvent, _resetBridgeForTesting,
} from "./event-bus-bridge";
export { _resetRepositoryForTesting, getMaxDepth } from "./repository";
export type {
  OrganizationStatus, OrganizationType, OrganizationRegistryEntry,
  TenantStatus, TenantEntry,
  InstitutionTypeEntry,
  HierarchyRelationshipType, HierarchyNode, HierarchyUpdate,
  CampusStatus, CampusEntry,
  DepartmentStatus, DepartmentEntry,
  FacultyStatus, FacultyEntry,
  WorkspaceType, WorkspaceStatus, WorkspaceEntry,
  MembershipRole, MembershipStatus, MembershipEntry,
  InvitationStatus, InvitationEntry,
  OrganizationBranding,
  ConfigScope as OrgConfigScope, OrganizationConfiguration,
  PolicyEnforcement, OrganizationPolicy,
  LifecycleTransition, LifecycleRecord,
  LicenseStatus, LicenseMetadataEntry,
  QuotaResource, QuotaStatus, QuotaEntry,
  DomainStatus, DomainEntry,
  IsolationBoundary, TenantIsolation,
  OrganizationAnalytics,
  AuditCategory as OrgAuditCategory, AuditOutcome as OrgAuditOutcome, OrganizationAuditRecord,
  OrganizationDashboard,
  OrganizationEventType,
  OrganizationDeveloperIntegration, OrganizationAdminStatus, OrganizationDocumentation,
} from "./types";
